baseurl = "https://yuniver.se/"
languageCode = "en-us"
title = "The Yuniverse"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "Welcome to my home"
  # "light" or "dark"
  defaultTheme = "dark"
  GATag = "UA-132882214-1"

[params.logo]
  logoText = "the yuniverse"
  # or
  #
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
#  [[menu.main]]
#    identifier = "showcase"
#    name = "Showcase"
#    url = "/showcase"
